apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitblit
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: gitblit
  storageClassName: do-block-storage
  volumeMode: Filesystem
