#modified from https://github.com/hexojs/hexo/blob/master/.github/workflows/tester.yml

name: Tester

on: [push, pull_request]

jobs:
  tester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['16.x', '18.x', '20.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Hexo
        run: npm install hexo-cli -g
      - name: Get Submodules
        run: |
          git submodule init
          git submodule update
          git submodule foreach git pull origin master
      - name: Install Dependencies
        run: npm install
      - name: Hexo Generate
        run: hexo generate
